# **1) Import Pandas**

In [6]:
import pandas as pd

# **2) Opening a local CSV file**

In [5]:
df = pd.read_csv('/content/student_placement_float_iq.csv') # Calling the dataset in the code.
df

    Serial_No  CGPA      IQ  Placement
0           1  2.59  107.36          0
1           2  2.94  115.82          0
2           3  3.96  108.43          1
3           4  2.36  120.12          0
4           5  3.06  125.65          1
..        ...   ...     ...        ...
95         96  3.95   98.77          1
96         97  3.87  134.28          1
97         98  3.30  139.24          1
98         99  3.80  105.87          1
99        100  2.56  112.09          0

[100 rows x 4 columns]

# **3) Opening a csv file from a url**

In [16]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}

req = requests.get(url, headers=headers)
data = StringIO(req.text)

df = pd.read_csv(data)

df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# **4) Sep Parameter**

In [26]:
df =  pd.read_csv('/content/ecommerce_orders_1000.tsv',sep='\t',names=['Order_ID','Customer_ID','Category','Product_Name','Quantity','Unit_Price','Total_Amount','Payment_Method','Order_Status'])
df

,Order_ID,Customer_ID,Category,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Order_Status
0,Order_ID,Customer_ID,Category,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Order_Status
1,ORD-10000,CUST-202,Clothing,Running Shoes,2,25.0,50.0,Mobile Banking,Delivered
2,ORD-10001,CUST-448,Electronics,Wireless Mouse,4,35.0,140.0,PayPal,Delivered
3,ORD-10002,CUST-370,Clothing,Men T-Shirt,1,15.5,15.5,Cash on Delivery,Shipped
4,ORD-10003,CUST-206,Electronics,Mechanical Keyboard,1,99.0,99.0,Cash on Delivery,Delivered
...,...,...,...,...,...,...,...,...,...
996,ORD-10995,CUST-326,Beauty,Sunscreen,3,85.0,255.0,PayPal,Delivered
997,ORD-10996,CUST-470,Electronics,USB-C Cable,5,12.0,60.0,Debit Card,Delivered
998,ORD-10997,CUST-114,Clothing,Hoodie,3,99.0,297.0,PayPal,Delivered
999,ORD-10998,CUST-291,Electronics,Smartwatch,1,25.0,25.0,Mobile Banking,Delivered
1000,ORD-10999,CUST-218,Beauty,Perfume,5,12.0,60.0,PayPal,Delivered

# **5) Index_col parameter**

In [27]:
df = pd.read_csv('/content/ecommerce_orders_1000.tsv',sep='\t',index_col=1)
df

,Order_ID,Category,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Order_Status
Customer_ID,,,,,,,,
CUST-202,ORD-10000,Clothing,Running Shoes,2,25.0,50.0,Mobile Banking,Delivered
CUST-448,ORD-10001,Electronics,Wireless Mouse,4,35.0,140.0,PayPal,Delivered
CUST-370,ORD-10002,Clothing,Men T-Shirt,1,15.5,15.5,Cash on Delivery,Shipped
CUST-206,ORD-10003,Electronics,Mechanical Keyboard,1,99.0,99.0,Cash on Delivery,Delivered
CUST-171,ORD-10004,Clothing,Running Shoes,5,35.0,175.0,Debit Card,Delivered
...,...,...,...,...,...,...,...,...
CUST-326,ORD-10995,Beauty,Sunscreen,3,85.0,255.0,PayPal,Delivered
CUST-470,ORD-10996,Electronics,USB-C Cable,5,12.0,60.0,Debit Card,Delivered
CUST-114,ORD-10997,Clothing,Hoodie,3,99.0,297.0,PayPal,Delivered
CUST-291,ORD-10998,Electronics,Smartwatch,1,25.0,25.0,Mobile Banking,Delivered
CUST-218,ORD-10999,Beauty,Perfume,5,12.0,60.0,PayPal,Delivered

# **6) Header parameter**

In [32]:
df = pd.read_csv('/content/corrupted_header_data.csv',header=1)
df

      Emp_ID    Name Department  Salary  Experience_Years  Performance_Score
0   EMP-2000   Sakib      Sales  108620                11               2.66
1   EMP-2001    Sami         HR   80977                 8               4.45
2   EMP-2002   Rahim  Marketing   83054                 7               2.67
3   EMP-2003   Rifat  Marketing   80127                 8               2.83
4   EMP-2004   Sakib  Marketing   87731                 8               4.32
..       ...     ...        ...     ...               ...                ...
95  EMP-2095    Sami    Finance   81125                 8               3.32
96  EMP-2096    Anik  Marketing  100120                 6               4.79
97  EMP-2097   Rifat         HR   90200                 8               2.72
98  EMP-2098  Tanvir    Finance   63063                12               4.64
99  EMP-2099  Tanvir         IT   92513                 2               3.17

[100 rows x 6 columns]

# **7) use_cols parameter**

In [33]:
df = pd.read_csv('/content/ecommerce_orders_1000.tsv',sep='\t',usecols=['Order_ID','Product_Name','Quantity','Unit_Price','Total_Amount'])
df

      Order_ID         Product_Name  Quantity  Unit_Price  Total_Amount
0    ORD-10000        Running Shoes         2        25.0          50.0
1    ORD-10001       Wireless Mouse         4        35.0         140.0
2    ORD-10002          Men T-Shirt         1        15.5          15.5
3    ORD-10003  Mechanical Keyboard         1        99.0          99.0
4    ORD-10004        Running Shoes         5        35.0         175.0
..         ...                  ...       ...         ...           ...
995  ORD-10995            Sunscreen         3        85.0         255.0
996  ORD-10996          USB-C Cable         5        12.0          60.0
997  ORD-10997               Hoodie         3        99.0         297.0
998  ORD-10998           Smartwatch         1        25.0          25.0
999  ORD-10999              Perfume         5        12.0          60.0

[1000 rows x 5 columns]

# **8) Skiprows Parameters**

In [41]:
df = pd.read_csv('/content/ecommerce_orders_1000.tsv',sep='\t',skiprows=[1,2,3])
df

,Order_ID,Customer_ID,Category,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Order_Status
0,ORD-10003,CUST-206,Electronics,Mechanical Keyboard,1,99.00,99.00,Cash on Delivery,Delivered
1,ORD-10004,CUST-171,Clothing,Running Shoes,5,35.00,175.00,Debit Card,Delivered
2,ORD-10005,CUST-288,Electronics,Bluetooth Headphones,5,85.00,425.00,Credit Card,Delivered
3,ORD-10006,CUST-120,Books,Fiction Novel,3,49.99,149.97,PayPal,Delivered
4,ORD-10007,CUST-202,Home & Kitchen,Desk Lamp,4,12.00,48.00,Cash on Delivery,Delivered
...,...,...,...,...,...,...,...,...,...
992,ORD-10995,CUST-326,Beauty,Sunscreen,3,85.00,255.00,PayPal,Delivered
993,ORD-10996,CUST-470,Electronics,USB-C Cable,5,12.00,60.00,Debit Card,Delivered
994,ORD-10997,CUST-114,Clothing,Hoodie,3,99.00,297.00,PayPal,Delivered
995,ORD-10998,CUST-291,Electronics,Smartwatch,1,25.00,25.00,Mobile Banking,Delivered
996,ORD-10999,CUST-218,Beauty,Perfume,5,12.00,60.00,PayPal,Delivered

# **9) nrows Parameters**

In [42]:
df = pd.read_csv('/content/ecommerce_orders_1000.tsv',sep='\t',nrows=100)
df

,Order_ID,Customer_ID,Category,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Order_Status
0,ORD-10000,CUST-202,Clothing,Running Shoes,2,25.00,50.00,Mobile Banking,Delivered
1,ORD-10001,CUST-448,Electronics,Wireless Mouse,4,35.00,140.00,PayPal,Delivered
2,ORD-10002,CUST-370,Clothing,Men T-Shirt,1,15.50,15.50,Cash on Delivery,Shipped
3,ORD-10003,CUST-206,Electronics,Mechanical Keyboard,1,99.00,99.00,Cash on Delivery,Delivered
4,ORD-10004,CUST-171,Clothing,Running Shoes,5,35.00,175.00,Debit Card,Delivered
...,...,...,...,...,...,...,...,...,...
95,ORD-10095,CUST-316,Clothing,Women Jeans,2,85.00,170.00,Debit Card,Delivered
96,ORD-10096,CUST-351,Books,Fiction Novel,4,15.50,62.00,Credit Card,Delivered
97,ORD-10097,CUST-287,Clothing,Women Jeans,3,199.99,599.97,Cash on Delivery,Delivered
98,ORD-10098,CUST-479,Books,Self-Help Guide,4,85.00,340.00,Credit Card,Delivered
99,ORD-10099,CUST-140,Clothing,Women Jeans,5,199.99,999.95,PayPal,Shipped

# **10) Encoding Parameter**

In [46]:
df = pd.read_csv('/content/latin1_encoded_dataset.csv',encoding='latin-1')
df

,Customer_ID,Name,City,Product,Purchase_Amount_EUR,Satisfaction_Rating
0,CUST-1000,García,München,Açaí Juice,24.08,2
1,CUST-1001,Sánchez,Córdoba,Açaí Juice,101.98,1
2,CUST-1002,Björn,München,Café Machine,28.95,2
3,CUST-1003,François,València,Crème Brûlée Mix,451.16,2
4,CUST-1004,Renée,Genève,Mañana Book,421.36,4
...,...,...,...,...,...,...
95,CUST-1095,Sánchez,València,Über-Jacket,318.29,4
96,CUST-1096,López,Nîmes,Chocolat au Lait,374.38,5
97,CUST-1097,Müller,Málaga,Würstchen,11.21,2
98,CUST-1098,Sánchez,Zürich,Café Machine,328.33,2
99,CUST-1099,Sánchez,Córdoba,Mañana Book,368.04,4

# **11) Skip bad lines**

In [52]:
df = pd.read_csv('/content/bad_lines_dataset.csv',on_bad_lines='skip')
df

     Order_ID Customer_Name     Product  Price      Status
0        1000         Karim      Laptop  37048     Pending
1        1001        Nayeem  Headphones  14434  Processing
2        1002         Karim     Speaker  56302   Delivered
3        1004          Anik     Speaker   4478  Processing
4        1005        Nayeem     Printer  55987     Pending
..        ...           ...         ...    ...         ...
115      1144         Sakib      Tablet   9161     Pending
116      1145         Rifat      Tablet  77556   Delivered
117      1146         Fahim      Tablet  63518   Delivered
118      1148          Anik     Printer  29906   Cancelled
119      1149        Nayeem    Keyboard  58125   Cancelled

[120 rows x 5 columns]

In [53]:
df = pd.read_csv('/content/bad_lines_dataset.csv',on_bad_lines='warn')
df

/tmp/ipykernel_2157/3897005974.py:1: ParserWarning: Skipping line 5: expected 5 fields, saw 7
Skipping line 9: expected 5 fields, saw 6
Skipping line 15: expected 5 fields, saw 7
Skipping line 19: expected 5 fields, saw 6
Skipping line 25: expected 5 fields, saw 7
Skipping line 29: expected 5 fields, saw 6
Skipping line 35: expected 5 fields, saw 7
Skipping line 39: expected 5 fields, saw 6
Skipping line 45: expected 5 fields, saw 7
Skipping line 49: expected 5 fields, saw 6
Skipping line 55: expected 5 fields, saw 7
Skipping line 59: expected 5 fields, saw 6
Skipping line 65: expected 5 fields, saw 7
Skipping line 69: expected 5 fields, saw 6
Skipping line 75: expected 5 fields, saw 7
Skipping line 79: expected 5 fields, saw 6
Skipping line 85: expected 5 fields, saw 7
Skipping line 89: expected 5 fields, saw 6
Skipping line 95: expected 5 fields, saw 7
Skipping line 99: expected 5 fields, saw 6
Skipping line 105: expected 5 fields, saw 7
Skipping line 109: expected 5 fields, saw 6
Skipping line 115: expected 5 fields, saw 7
Skipping line 119: expected 5 fields, saw 6
Skipping line 125: expected 5 fields, saw 7
Skipping line 129: expected 5 fields, saw 6
Skipping line 135: expected 5 fields, saw 7
Skipping line 139: expected 5 fields, saw 6
Skipping line 145: expected 5 fields, saw 7
Skipping line 149: expected 5 fields, saw 6

  df = pd.read_csv('/content/bad_lines_dataset.csv',on_bad_lines='warn')

     Order_ID Customer_Name     Product  Price      Status
0        1000         Karim      Laptop  37048     Pending
1        1001        Nayeem  Headphones  14434  Processing
2        1002         Karim     Speaker  56302   Delivered
3        1004          Anik     Speaker   4478  Processing
4        1005        Nayeem     Printer  55987     Pending
..        ...           ...         ...    ...         ...
115      1144         Sakib      Tablet   9161     Pending
116      1145         Rifat      Tablet  77556   Delivered
117      1146         Fahim      Tablet  63518   Delivered
118      1148          Anik     Printer  29906   Cancelled
119      1149        Nayeem    Keyboard  58125   Cancelled

[120 rows x 5 columns]

In [54]:
df = pd.read_csv('/content/bad_lines_dataset.csv',on_bad_lines='error')
df

ParserError: Error tokenizing data. C error: Expected 5 fields in line 5, saw 7

# **12) dtype Parameter**

In [57]:
df = pd.read_csv('/content/ecommerce_orders_1000.tsv',sep='\t')
df.info()
df = pd.read_csv('/content/ecommerce_orders_1000.tsv',sep='\t',dtype={'Quantity':'float'})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        1000 non-null   object
 1   Customer_ID     1000 non-null   object
 2   Category        1000 non-null   object
 3   Product_Name    1000 non-null   object
 4   Quantity        1000 non-null   int64
 5   Unit_Price      1000 non-null   float64
 6   Total_Amount    1000 non-null   float64
 7   Payment_Method  1000 non-null   object
 8   Order_Status    1000 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 70.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        1000 non-null   object
 1   Customer_ID     1000 non-null   object
 2   Category        1000 non-null   object
 3   Product_Name    1000 non-null   object
 4   Quantity        1000 non-null   float64
 5   Unit_Price      1000 non-null   float64
 6   Total_Amount    1000 non-null   float64
 7   Payment_Method  1000 non-null   object
 8   Order_Status    1000 non-null   object
dtypes: float64(3), object(6)
memory usage: 70.4+ KB

# **13) Handling Dates**

In [60]:
df = pd.read_csv('/content/string_date_dataset.csv')
df.info()
df = pd.read_csv('/content/string_date_dataset.csv',parse_dates=['Joining_Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Emp_ID        100 non-null    object
 1   Name          100 non-null    object
 2   Joining_Date  100 non-null    object
 3   Salary        100 non-null    int64
dtypes: int64(1), object(3)
memory usage: 3.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Emp_ID        100 non-null    object
 1   Name          100 non-null    object
 2   Joining_Date  100 non-null    datetime64[ns]
 3   Salary        100 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 3.3+ KB

In [61]:
df = pd.read_csv('/content/split_date_dataset.csv')
df.info()
df = pd.read_csv('/content/split_date_dataset.csv',parse_dates={'Date':['Month','Day','Year']})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  100 non-null    object
 1   Year      100 non-null    int64
 2   Month     100 non-null    int64
 3   Day       100 non-null    int64
 4   Product   100 non-null    object
 5   Amount    100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      100 non-null    datetime64[ns]
 1   Order_ID  100 non-null    object
 2   Product   100 non-null    object
 3   Amount    100 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 3.3+ KB

/tmp/ipykernel_2157/993991645.py:3: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  df = pd.read_csv('/content/split_date_dataset.csv',parse_dates={'Date':['Month','Day','Year']})

# **14) Convertors**

In [62]:
df = pd.read_csv('/content/ipl_comprehensive_complete_dataset.csv')
df

,Match_ID,Season,Date,Venue,Team_1,Team_2,Toss_Winner,Toss_Decision,Winner,Loser,Win_By_Runs,Win_By_Wickets,Player_Of_The_Match,Top_Scorer,Top_Scorer_Runs,Top_Wicket_Taker,Top_Wicket_Taker_Wickets
0,10001,2008,2008-04-18,"Eden Gardens, Kolkata",Lucknow Super Giants,Chennai Super Kings,Lucknow Super Giants,bat,Lucknow Super Giants,Chennai Super Kings,28,0,Ravi Bishnoi,Quinton de Kock,74,Quinton de Kock,2
1,10002,2008,2008-04-20,"Rajiv Gandhi International Stadium, Hyderabad",Chennai Super Kings,Punjab Kings,Punjab Kings,field,Punjab Kings,Chennai Super Kings,0,3,Kagiso Rabada,Deepak Chahar,47,Arshdeep Singh,4
2,10003,2008,2008-04-22,"MA Chidambaram Stadium, Chennai",Lucknow Super Giants,Mumbai Indians,Lucknow Super Giants,field,Mumbai Indians,Lucknow Super Giants,6,0,Hardik Pandya,Quinton de Kock,88,Ishan Kishan,4
3,10004,2008,2008-04-24,"M. Chinnaswamy Stadium, Bengaluru",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,Gujarat Titans,Lucknow Super Giants,67,0,Rashid Khan,Rashid Khan,118,Rahul Tewatia,3
4,10005,2008,2008-04-26,"PCA Stadium, Mohali",Mumbai Indians,Chennai Super Kings,Mumbai Indians,field,Mumbai Indians,Chennai Super Kings,0,9,Ishan Kishan,Rohit Sharma,115,Rohit Sharma,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202,11203,2026,2026-08-23,"Sawai Mansingh Stadium, Jaipur",Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,Mumbai Indians,0,4,Deepak Chahar,Suryakumar Yadav,64,MS Dhoni,3
1203,11204,2026,2026-08-26,"Ekana Cricket Stadium, Lucknow",Punjab Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,Punjab Kings,47,0,Travis Head,Sam Curran,58,Heinrich Klaasen,2
1204,11205,2026,2026-08-28,"PCA Stadium, Mohali",Delhi Capitals,Lucknow Super Giants,Lucknow Super Giants,bat,Delhi Capitals,Lucknow Super Giants,0,2,David Warner,Axar Patel,98,David Warner,2
1205,11206,2026,2026-08-30,"MA Chidambaram Stadium, Chennai",Rajasthan Royals,Lucknow Super Giants,Lucknow Super Giants,field,Rajasthan Royals,Lucknow Super Giants,72,0,Trent Boult,Ravi Bishnoi,86,Yashasvi Jaiswal,2
1206,11207,2026,2026-09-01,"Rajiv Gandhi International Stadium, Hyderabad",Mumbai Indians,Delhi Capitals,Mumbai Indians,bat,Delhi Capitals,Mumbai Indians,0,6,Kuldeep Yadav,Ishan Kishan,61,Rishabh Pant,3

In [64]:
def shorten_team_name(team):
    mapping = {
        "Royal Challengers Bengaluru": "RCB",
        "Chennai Super Kings": "CSK",
        "Mumbai Indians": "MI",
        "Kolkata Knight Riders": "KKR",
        "Rajasthan Royals": "RR",
        "Sunrisers Hyderabad": "SRH",
        "Delhi Capitals": "DC",
        "Punjab Kings": "PBKS",
        "Lucknow Super Giants": "LSG",
        "Gujarat Titans": "GT"
    }
    return mapping.get(team, team)


df = pd.read_csv('ipl_comprehensive_complete_dataset.csv', converters={
    'Team_1': shorten_team_name,
    'Team_2': shorten_team_name,
    'Winner': shorten_team_name,
    'Loser': shorten_team_name
})


df.head()

,Match_ID,Season,Date,Venue,Team_1,Team_2,Toss_Winner,Toss_Decision,Winner,Loser,Win_By_Runs,Win_By_Wickets,Player_Of_The_Match,Top_Scorer,Top_Scorer_Runs,Top_Wicket_Taker,Top_Wicket_Taker_Wickets
0,10001,2008,2008-04-18,"Eden Gardens, Kolkata",LSG,CSK,Lucknow Super Giants,bat,LSG,CSK,28,0,Ravi Bishnoi,Quinton de Kock,74,Quinton de Kock,2
1,10002,2008,2008-04-20,"Rajiv Gandhi International Stadium, Hyderabad",CSK,PBKS,Punjab Kings,field,PBKS,CSK,0,3,Kagiso Rabada,Deepak Chahar,47,Arshdeep Singh,4
2,10003,2008,2008-04-22,"MA Chidambaram Stadium, Chennai",LSG,MI,Lucknow Super Giants,field,MI,LSG,6,0,Hardik Pandya,Quinton de Kock,88,Ishan Kishan,4
3,10004,2008,2008-04-24,"M. Chinnaswamy Stadium, Bengaluru",LSG,GT,Gujarat Titans,field,GT,LSG,67,0,Rashid Khan,Rashid Khan,118,Rahul Tewatia,3
4,10005,2008,2008-04-26,"PCA Stadium, Mohali",MI,CSK,Mumbai Indians,field,MI,CSK,0,9,Ishan Kishan,Rohit Sharma,115,Rohit Sharma,2

# **15) na_values Parameter**

In [65]:
df = pd.read_csv('/content/na_values_practice_dataset.csv')
df.head()

     Emp_ID    Name   Department  Salary Performance_Score  Joining_Year
0  EMP-1001   Fahim      Finance   52167              4.48        2015.0
1  EMP-1002    Anik        Sales   66798                 ?        2025.0
2  EMP-1003  Nayeem          NaN  103617              4.64        2016.0
3  EMP-1004     NaN          ???  128255              3.67        2025.0
4  EMP-1005   Sakib  Engineering    -999              2.72        2016.0

In [67]:
custom_na = ['N/A', 'missing', '?', 'null', 'None', '???', '-999', -999]

df = pd.read_csv('/content/na_values_practice_dataset.csv',na_values=custom_na)
df.head()

     Emp_ID    Name   Department    Salary  Performance_Score  Joining_Year
0  EMP-1001   Fahim      Finance   52167.0               4.48        2015.0
1  EMP-1002    Anik        Sales   66798.0                NaN        2025.0
2  EMP-1003  Nayeem          NaN  103617.0               4.64        2016.0
3  EMP-1004     NaN          NaN  128255.0               3.67        2025.0
4  EMP-1005   Sakib  Engineering       NaN               2.72        2016.0

# **16) Loading a huge dataset in chunks**

In [69]:
df = pd.read_csv('/content/ecommerce_orders_1000.tsv',sep='\t',chunksize=100)

In [70]:
for chunks in df:
  print(chunks.shape)

(100, 9)
(100, 9)
(100, 9)
(100, 9)
(100, 9)
(100, 9)
(100, 9)
(100, 9)
(100, 9)
(100, 9)